### ISSUE TITLE
Browse function 

### ISSUE THREAD

**Issue by Henrytje** [olejon/spotcommander#132] opened 2019-03-13 19:57 UTC
When discovering new music via the browse function, it says in spotify 'link not found'. Could this be solved easily? Using free version (spotify 0.9) and Ubuntu 18.04. 

Kind regards, 

Henry

**Comment by olejon** [comment] 2019-03-20 14:16
Thank you. The Browse feature goes (encrypted) through my server, in case of such situations. I will see when I have time, hopefully in the coming days, if this simply can be fixed on the server side so no update to SpotCommander is needed. I just checked Spotify 0.9 on Arch Linux because of a bug in one of the dependencies of my AUR package `spotify-legacy`. Then I also installed SpotCommander to check, and saw also Playlists shows "garbage" under the name of the Playlist where it should show the username of the creator of the Playlist. Also no cover art on the Playlist page. This may suggest Spotify have changed the URI object key from the API or the Playlist URI syntax (which is hard coded using RegEx in SpotCommander to distinguish them from other types like artists and tracks, since they all have a fixed syntax, like `spotify: artist:xNumberOfCharacters`). Cover art fetching for some items also goes through my server because of the sizes/stability etc. I'll see... I hope no update to SpotCommander itself is necessary. That's more of a job. Especially when my plan for a future version is a complete overhaul using Google's new Material web components in a Node.js environment. But can always just fix the bugs. Really the biggest job there is the packaging.

**Comment by Henrytje** [comment] 2019-03-20 19:03
Popular playlists are working fine!

**Comment by olejon** [comment] 2019-03-20 19:28
Ok. And what about Playlists found in Search? Let's say you search for Kygo, scroll down to the "Playlists" section (big cover art) and go into it and play. Does that work? Sorry I'm "on the move" so can't check right now.

**Comment by Henrytje** [comment] 2019-03-20 20:11
Those don't work. That's ok, happy to help and use your app on a daily basis :)

**Comment by atatdotdot** [comment] 2019-06-19 10:31
I have realized that the issue I just created https://github.com/olejon/spotcommander/issues/134 seems to be caused by the same underlying problem as this one; apologies for the duplication.

**Comment by olejon** [comment] 2019-07-11 10:57
See my comment on #134

**Comment by olejon** [comment] 2019-07-11 13:30
Please see [this issue's comment](https://github.com/olejon/spotcommander/issues/134#issuecomment-510477870).

**Closed** 2019-07-11 18:21 UTC
Labels: bug, bug-caused-by-spotify
